//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.2.4-2 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2014.11.11 at 09:53:04 PM CET 
//


package pl.drabik.opensongcleaner.opensong;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the pl.drabik.opensongcleaner.opensong package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _Song_QNAME = new QName("", "song");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: pl.drabik.opensongcleaner.opensong
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link OpenSongSong }
     * 
     */
    public OpenSongSong createOpenSongSong() {
        return new OpenSongSong();
    }

    /**
     * Create an instance of {@link CapoType }
     * 
     */
    public CapoType createCapoType() {
        return new CapoType();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link OpenSongSong }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "song")
    public JAXBElement<OpenSongSong> createSong(OpenSongSong value) {
        return new JAXBElement<OpenSongSong>(_Song_QNAME, OpenSongSong.class, null, value);
    }

}
